boshliq/urls.py
from django.urls import path
from .views import home, xodim_page,xodim_delete,xodim_qoshish,tovarlar_page,tovar_add_page,tovar_add_save,tovar_shtrix_code,tovar_tahrirlash,tovar_tahrirlash_save,tovar_delete
app_name = 'boshliq'

urlpatterns = [
    path('home/',home,name="admin_home"),
    path('xodimlar-boshqaruv/', xodim_page, name="xodim_page"),
    path('xodim-ochirish/<int:id>',xodim_delete, name="xodim_delete"),
    path('xodim_qoshish',xodim_qoshish, name="xodim_qoshish"),
    path('tovarlar/',tovarlar_page,name="tovarlar_page"),
    path('tovar-qoshish/',tovar_add_page,name="tovar_add_page"),
    path('tovar_add_save',tovar_add_save,name="tovar_add_save"),
    path('tovar_shtrix_code',tovar_shtrix_code,name="tovar_shtrix_code"),
    path('tovar_tahrirlash/<int:id>',tovar_tahrirlash,name="tovar_tahrirlash"),
    path('tovar_tahrirlash_save',tovar_tahrirlash_save,name="tovar_tahrirlash_save"),
    path('tovar_delete/<int:id>',tovar_delete, name="tovar_delete"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boshliq/', include('boshliq.urls')),
    path('', include('accounts.urls')),
    path('sotuvchi/', include('sotuvchi.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/aza.png' %}" type="image/x-icon">
    <title>{% block title %} {% endblock title %}</title>
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/icofont.css' %}">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/themify.css' %}">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/flag-icon.css' %}">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/feather-icon.css' %}">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/scrollbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/chartist.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/date-picker.css' %}">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/bootstrap.css' %}">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/table.css' %}">
    <link id="color" rel="stylesheet" href="{% static 'assets/css/color-1.css' %}" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'date/style/style.css' %}">
  </head>
  <body class="dark-only" onload="startTime()">
    <div class="loader-wrapper">
      <div class="loader-index"><span></span></div>
      <svg>
        <defs></defs>
        <filter id="goo">
          <fegaussianblur in="SourceGraphic" stddeviation="11" result="blur"></fegaussianblur>
          <fecolormatrix in="blur" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo"> </fecolormatrix>
        </filter>
      </svg>
    </div>
    <!-- tap on top starts-->
    <div class="tap-top"><i data-feather="chevrons-up"></i></div>
    <!-- tap on tap ends-->
    <!-- page-wrapper Start-->
    <div class="page-wrapper compact-wrapper" id="pageWrapper">
      <!-- Page Header Start-->
      <div class="page-header">
        <div class="header-wrapper row m-0">
          
          <div class="header-logo-wrapper col-auto p-0">
            <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="{% static 'assets/images/logo/logo.png' %}" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="align-center"></i></div>
          </div>
          <div class="left-header col horizontal-wrapper ps-0">
            <ul class="horizontal-menu">

            </ul>
          </div>
          <div class="nav-right col-8 pull-right right-header p-0">
            <ul class="nav-menus">
              
             
              <li class="profile-nav onhover-dropdown p-0 me-0">
                <div class="media profile-media">
                  <div class="media-body"><span>{{ request.user.username.title }}</span>
                    <i class="middle fa fa-angle-down"></i>
                  </div>
                </div>
                <ul class="profile-dropdown onhover-show-div" style="left: -50px !important; margin-top: -25px !important;">
                  <li><a href="{% url 'logout' %}"><i data-feather="log-in"> </i><span>Log out</span></a></li>
                </ul>
              </li>
            </ul>
          </div>
          
        </div>
      </div>
      <!-- Page Header Ends                              -->
      <!-- Page Body Start-->
      <div class="page-body-wrapper">
        <!-- Page Sidebar Start-->
          {% include 'sidebar.html' %}
        <!-- Page Sidebar Ends-->
        {% block content %}

        {% endblock content %}
        <!-- footer start-->
        <footer class="footer" style="margin: 0px !important; ">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12 footer-copyright text-center">
                <p class="mb-0">Copyright 2022 © GeekZoNe theme by Azizbek  </p>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <!-- latest jquery-->
    <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap js-->
    <script src="{% static 'assets/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <!-- feather icon js-->
    <script src="{% static 'assets/js/icons/feather-icon/feather.min.js' %}"></script>
    <script src="{% static 'assets/js/icons/feather-icon/feather-icon.js' %}"></script>
    <!-- scrollbar js-->
    <script src="{% static 'assets/js/scrollbar/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/scrollbar/custom.js' %}"></script>
    <!-- Sidebar jquery-->
    <script src="{% static 'assets/js/config.js' %}"></script>
    <!-- Plugins JS start-->
    <script src="{% static 'assets/js/sidebar-menu.js' %}"></script>
    <script src="{% static 'assets/js/chart/chartist/chartist.js' %}"></script>
    <script src="{% static 'assets/js/chart/chartist/chartist-plugin-tooltip.js' %}"></script>
    <script src="{% static 'assets/js/chart/knob/knob.min.js' %}"></script>
    <script src="{% static 'assets/js/chart/knob/knob-chart.js' %}"></script>
    <script src="{% static 'assets/js/chart/apex-chart/apex-chart.js' %}"></script>
    <script src="{% static 'assets/js/chart/apex-chart/stock-prices.js' %}"></script>
    <!-- <script src="{% static 'assets/js/notify/bootstrap-notify.min.js' %}"></script> -->
    <script src="{% static 'assets/js/dashboard/default.js' %}"></script>
    <script src="{% static 'assets/js/notify/index.js' %}"></script>
    <script src="{% static 'assets/js/datepicker/date-picker/datepicker.js' %}"></script>
    <script src="{% static 'assets/js/datepicker/date-picker/datepicker.en.js' %}"></script>
    <script src="{% static 'assets/js/datepicker/date-picker/datepicker.custom.js' %}"></script>
    <script src="{% static 'assets/js/typeahead/handlebars.js' %}"></script>
    <script src="{% static 'assets/js/typeahead/typeahead.bundle.js' %}"></script>
    <script src="{% static 'assets/js/typeahead/typeahead.custom.js' %}"></script>
    <script src="{% static 'assets/js/typeahead-search/handlebars.js' %}"></script>
    <script src="{% static 'assets/js/typeahead-search/typeahead-custom.js' %}"></script>
    <script src="{%static 'date/js/main.js' %}"></script>
    <!-- Plugins JS Ends-->
    <!-- Theme js-->
    <script src="{% static 'assets/js/script.js' %}"></script>
    <!-- login js-->
    <!-- Plugin used-->' %}
  </body>
</html>

templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Kirish</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'login/images/img-01.png' %}" alt="IMG">
				</div>

				<form method="post" action="/dologin" class="login100-form validate-form">
                    {% csrf_token %}
					<span class="login100-form-title">
						Saytga kirish
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Username xato kiritildi!!!">
						<input class="input100" type="text" name="username" placeholder="Username kiriting" autocomplete="off">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Parol xato kiritildi!!!">
						<input class="input100" type="password" name="password" placeholder="Parol kiriting">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Kirish
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

templates/pagination.html
<div class="clearfix">
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item disabled">
          <a href="?page={{ page.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active">
            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
        </li>
      {% else %}
        <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page.has_next %}
      <li class="page-item">
        <a href="?page={{ page.next_page_number }}" class="page-link"
          ><i class="fa fa-angle-double-right"></i
        ></a>
      </li>
      {% endif %}
    </ul>
  </div>

templates/sidebar.html
{% load static %}
<div class="sidebar-wrapper">
    <div>
      <div class="logo-wrapper"><a href="index.html"><img class="img-fluid for-light" src="{% static 'assets/images/logo/logo.png' %}" alt=""><img style="width: 80px; height: 40px;" class="img-fluid for-dark" src="{% static 'assets/images/logo/aza.png' %}" alt=""></a>
        <div class="back-btn"><i class="fa fa-angle-left"></i></div>
        <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
      </div>
      <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="{% static 'assets/images/logo/logo-icon.png' %}" alt=""></a></div>
      <nav class="sidebar-main">
        <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
        <div id="sidebar-menu">
            <ul class="sidebar-links" id="simple-bar">
              <li class="back-btn"><a href="index.html"><img class="img-fluid" src="{% static 'assets/images/logo/logo-icon.png' %}" alt=""></a>
                <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
              </li>
              <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="{% url 'boshliq:xodim_page' %}"><span>Xodimlar Boshqaruv</span></a>
              </li>

              <li class="sidebar-list"><a class="sidebar-link sidebar-title " href="{% url 'boshliq:tovarlar_page' %}"><span>Tovarlar</span></a>
              </li>


              <li class="sidebar-list"><a class="sidebar-link sidebar-title" href="{% url 'logout' %}"><span>Chiqish</span></a>
              </li>


            </ul>

        </div>
        <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
      </nav>
    </div>
  </div>